# Generated by Django 2.2.6 on 2019-11-25 03:02

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import media.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("media", models.FileField(upload_to=media.utils.UniqueFileName())),
                ("name", models.TextField(blank=True, default="")),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rendition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("large", "large"),
                            ("medium", "medium"),
                            ("small", "small"),
                            ("thumbnail", "thumbnail"),
                        ],
                        max_length=255,
                    ),
                ),
                ("media", models.FileField(upload_to=media.utils.UniqueFileName())),
                (
                    "original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renditions",
                        to="media.Media",
                    ),
                ),
            ],
            options={"unique_together": {("original", "resolution")}},
        ),
    ]
